
[jwt]
  expire_duration = 24
  secret = "i1ydX9RtHyuJTrw7frcu"

[language]
  local = "zh-cn"

# mysql 配置
[mysql]

  [mysql.base]
    # 连接最大时间
    conn_max_life_time = 60
    # 最大空闲连接数
    max_idle_conn = 60
    # 最大连接数
    max_open_conn = 10
  # mysql 读配置
  [mysql.read]
    addr = "10.10.1.35:3306"
    name = "short_url"
    pass = "Leyun123"
    user = "root"
  # mysql写配置
  [mysql.write]
    addr = "10.10.1.35:3306"
    name = "short_url"
    pass = "Leyun123"
    user = "root"
# redis 配置
[redis]
  addr = "127.0.0.1:6379"
  db = "0"
  # 最大重试次数
  max_retries = 3
  # 最小空闲连接
  min_idle_conn = 5
  pass = ""
  # 连接池大小
  pool_size = 10

# 服务配置
[server]
    port = ":3030"

[common]
# short urls that will be filtered to use
black_short_urls = ["version","health","short","expand","css","js","fuck","stupid"]

# Base string used to generate short url
base_string = "Ds3K9ZNvWmHcakr1oPnxh4qpMEzAye8wX5IdJ2LFujUgtC07lOTb6GYBQViSfR"

# Short url service domain name. This is used to filter short url loop.
domain_name = "127.0.0.1:3030"

schema = "http"

# 配置域名开始长度（1-62）
domain_length = 5